// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

/** Public project defaults for native APK when CI secrets were not injected. Anon key is public by design. */
const FALLBACK_URL = 'https://rqjchjytqcqjmljahcdr.supabase.co';
const FALLBACK_ANON =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxamNoanl0cWNxam1samFoY2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwMjAwMzMsImV4cCI6MjEwMjU5NjAzM30.JWffmq5TIUnizWR-DIhwLylmHPmuuks2kUuEDEidlE8';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function resolveConfig(): { url: string; key: string } {
  const fromViteUrl = (import.meta as ImportMeta & { env?: Record<string, string> }).env?.[
    'VITE_SUPABASE_URL'
  ];
  const fromViteKey = (import.meta as ImportMeta & { env?: Record<string, string> }).env?.[
    'VITE_SUPABASE_PUBLISHABLE_KEY'
  ];
  const fromProcessUrl =
    typeof process !== 'undefined' ? process.env?.['SUPABASE_URL'] || process.env?.['VITE_SUPABASE_URL'] : undefined;
  const fromProcessKey =
    typeof process !== 'undefined'
      ? process.env?.['SUPABASE_PUBLISHABLE_KEY'] ||
        process.env?.['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
        process.env?.['VITE_SUPABASE_ANON_KEY']
      : undefined;

  const url = String(fromViteUrl || fromProcessUrl || FALLBACK_URL).trim();
  const key = String(fromViteKey || fromProcessKey || FALLBACK_ANON).trim();
  return { url, key };
}

function createSupabaseClient(): SupabaseClient<Database> {
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = resolveConfig();

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error('[Supabase] Missing URL or publishable key after fallbacks');
    // Last-resort dummy so the UI can render login instead of white error boundary
    return createClient<Database>(FALLBACK_URL, FALLBACK_ANON, {
      auth: {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: false,
        flowType: 'pkce',
      },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
  });
}

let _supabase: SupabaseClient<Database> | undefined;

export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      try {
        _supabase = createSupabaseClient();
      } catch (e) {
        console.error('[Supabase] client init failed', e);
        _supabase = createClient<Database>(FALLBACK_URL, FALLBACK_ANON, {
          auth: {
            storage: brokeredPreviewStorage(),
            persistSession: true,
            autoRefreshToken: true,
            detectSessionInUrl: false,
            flowType: 'pkce',
          },
        });
      }
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
